config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :authors_books
  has_many :books, through: :authors_books
  validates :name, presence: true
end

app/models/authors_book.rb
class AuthorsBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :authors_books
  has_many :authors, through: :authors_books
  has_many :reviews
  validates :title, :pages, :year, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  validates :title, :content, :rating, :book_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def book_average_rating(book)
    arr = book.reviews.pluck(:rating)
    average = arr.inject{ |sum, el| sum + el }.to_f / arr.size
    number_with_precision(average, :precision => 2)
  end

  def book_review_count(book)
    book.reviews.count
  end

  def get_authors(book)
    authors = []
    book.authors.each do |author|
      authors << author.name
    end
    authors.join(', ')
  end
end

app/views/books/index.html.erb
<div class="container">
  <div class="book-index-list">
    <div class="row">
      <% @books.each do |book| %>
        <div class="col-sm-6 col-md-4">
          <div class="card book-card">
            <div class="card-body">
              <h5 class="card-title"><%= link_to book.title, book_path(book) %></h5>
              <h6 class="card-subtitle mb-2"><%= get_authors(book) %></h6>
              <div class="card-text-area">
              <p class="card-text">Rating: <%= book_average_rating(book) %></p>
              <p class="card-text">Reviews: <%= book_review_count(book) %></p>
              <p class="card-text">Pages: <%= book.pages %></p>
              <p class="card-text">Year: <%= book.year %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= @book.title %>
<%= get_authors(@book) %>
<%= @book.pages %>
<%= @book.year %>

<% @book.reviews.each do |review| %>
  <%= review.title %>
  <%= review.rating %>
  <%= review.content %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>